apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-rollout-sample-app
  namespace: default
spec:
  replicas: 5
  strategy:
    canary:
      # 단계별 카나리 트래픽 비중 및 대기 시간 설정
      steps:
      - setWeight: 20
      - pause: { duration: 2m } # 2분간 20% 카나리 상태 유지 후 자동 진행
      - setWeight: 50
      - pause: { duration: 5m }
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argo-rollout-sample-app
  template:
    metadata:
      labels:
        app: argo-rollout-sample-app
    spec:
      containers:
      - name: argo-rollout-sample-app
        image: 192.168.88.139/library/sample-app:1
        ports:
        - containerPort: 8080
